// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.proto

package log

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	trillian "github.com/google/trillian"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// InternalMessage has the details of a message that is going to
// be sent under the corporate account. It contains details that
// wouldn't be sent to the Tritter service, such as username of
// the user that made the request.
type InternalMessage struct {
	User                 string               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InternalMessage) Reset()         { *m = InternalMessage{} }
func (m *InternalMessage) String() string { return proto.CompactTextString(m) }
func (*InternalMessage) ProtoMessage()    {}
func (*InternalMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{0}
}

func (m *InternalMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalMessage.Unmarshal(m, b)
}
func (m *InternalMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalMessage.Marshal(b, m, deterministic)
}
func (m *InternalMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalMessage.Merge(m, src)
}
func (m *InternalMessage) XXX_Size() int {
	return xxx_messageInfo_InternalMessage.Size(m)
}
func (m *InternalMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalMessage.DiscardUnknown(m)
}

var xxx_messageInfo_InternalMessage proto.InternalMessageInfo

func (m *InternalMessage) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *InternalMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *InternalMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type LogProof struct {
	Root                 *trillian.SignedLogRoot `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Proof                *trillian.Proof         `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *LogProof) Reset()         { *m = LogProof{} }
func (m *LogProof) String() string { return proto.CompactTextString(m) }
func (*LogProof) ProtoMessage()    {}
func (*LogProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{1}
}

func (m *LogProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogProof.Unmarshal(m, b)
}
func (m *LogProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogProof.Marshal(b, m, deterministic)
}
func (m *LogProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogProof.Merge(m, src)
}
func (m *LogProof) XXX_Size() int {
	return xxx_messageInfo_LogProof.Size(m)
}
func (m *LogProof) XXX_DiscardUnknown() {
	xxx_messageInfo_LogProof.DiscardUnknown(m)
}

var xxx_messageInfo_LogProof proto.InternalMessageInfo

func (m *LogProof) GetRoot() *trillian.SignedLogRoot {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *LogProof) GetProof() *trillian.Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

type LogRequest struct {
	Message              *InternalMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LogRequest) Reset()         { *m = LogRequest{} }
func (m *LogRequest) String() string { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()    {}
func (*LogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{2}
}

func (m *LogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRequest.Unmarshal(m, b)
}
func (m *LogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRequest.Marshal(b, m, deterministic)
}
func (m *LogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRequest.Merge(m, src)
}
func (m *LogRequest) XXX_Size() int {
	return xxx_messageInfo_LogRequest.Size(m)
}
func (m *LogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogRequest proto.InternalMessageInfo

func (m *LogRequest) GetMessage() *InternalMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

type LogResponse struct {
	Proof                *LogProof `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LogResponse) Reset()         { *m = LogResponse{} }
func (m *LogResponse) String() string { return proto.CompactTextString(m) }
func (*LogResponse) ProtoMessage()    {}
func (*LogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{3}
}

func (m *LogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogResponse.Unmarshal(m, b)
}
func (m *LogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogResponse.Marshal(b, m, deterministic)
}
func (m *LogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogResponse.Merge(m, src)
}
func (m *LogResponse) XXX_Size() int {
	return xxx_messageInfo_LogResponse.Size(m)
}
func (m *LogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogResponse proto.InternalMessageInfo

func (m *LogResponse) GetProof() *LogProof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func init() {
	proto.RegisterType((*InternalMessage)(nil), "log.InternalMessage")
	proto.RegisterType((*LogProof)(nil), "log.LogProof")
	proto.RegisterType((*LogRequest)(nil), "log.LogRequest")
	proto.RegisterType((*LogResponse)(nil), "log.LogResponse")
}

func init() { proto.RegisterFile("log.proto", fileDescriptor_a153da538f858886) }

var fileDescriptor_a153da538f858886 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x50, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0xfd, 0xfa, 0xb5, 0x56, 0xbb, 0x41, 0x2b, 0x8b, 0x68, 0xc8, 0xc5, 0x12, 0x11, 0x4a, 0x95,
	0x0d, 0x44, 0x0f, 0x1e, 0x3c, 0x79, 0x13, 0x22, 0x48, 0xf4, 0xe4, 0xc1, 0x92, 0xd4, 0xed, 0x74,
	0x61, 0x93, 0x89, 0xbb, 0x93, 0x83, 0xff, 0x5e, 0xba, 0xdb, 0x34, 0xe0, 0x69, 0x77, 0xde, 0xbc,
	0x37, 0x6f, 0xde, 0xb0, 0x89, 0x46, 0x10, 0x8d, 0x41, 0x42, 0x3e, 0xd4, 0x08, 0xd1, 0x09, 0x19,
	0xa5, 0xb5, 0x2a, 0x6a, 0x0f, 0x46, 0xe7, 0x5d, 0xbd, 0xd4, 0x08, 0xcb, 0xa2, 0x51, 0x3b, 0xfc,
	0x12, 0x10, 0x41, 0xcb, 0xc4, 0x55, 0x65, 0xbb, 0x4e, 0x48, 0x55, 0xd2, 0x52, 0x51, 0x35, 0x9e,
	0x10, 0xff, 0xb0, 0xe9, 0x73, 0x4d, 0xd2, 0xd4, 0x85, 0x7e, 0x91, 0xd6, 0x16, 0x20, 0x39, 0x67,
	0xa3, 0xd6, 0x4a, 0x13, 0x0e, 0x66, 0x83, 0xf9, 0x24, 0x77, 0x7f, 0x1e, 0xb2, 0xc3, 0xca, 0xb7,
	0xc3, 0xff, 0x0e, 0xee, 0x4a, 0xfe, 0xc0, 0x26, 0xfb, 0x99, 0xe1, 0x70, 0x36, 0x98, 0x07, 0x69,
	0x24, 0xbc, 0xab, 0xe8, 0x5c, 0xc5, 0x7b, 0xc7, 0xc8, 0x7b, 0x72, 0xfc, 0xc9, 0x8e, 0x32, 0x84,
	0x57, 0x83, 0xb8, 0xe6, 0x37, 0x6c, 0x64, 0x10, 0xc9, 0x79, 0x06, 0xe9, 0x85, 0xd8, 0xc7, 0x7b,
	0x53, 0x50, 0xcb, 0xaf, 0x0c, 0x21, 0x47, 0xa4, 0xdc, 0x91, 0xf8, 0x35, 0x3b, 0x68, 0xb6, 0x2a,
	0xb7, 0x4a, 0x90, 0x4e, 0x7b, 0xb6, 0x1b, 0x96, 0xfb, 0x6e, 0xfc, 0xc8, 0xd8, 0x56, 0x27, 0xbf,
	0x5b, 0x69, 0x89, 0x8b, 0x3e, 0x81, 0x37, 0x39, 0x13, 0xdb, 0x9b, 0xfe, 0x09, 0xbf, 0xcf, 0x15,
	0xa7, 0x2c, 0x70, 0x6a, 0xdb, 0x60, 0x6d, 0x25, 0xbf, 0xea, 0x3c, 0xbd, 0xf8, 0xd8, 0x89, 0xbb,
	0xf5, 0x77, 0x8e, 0xe9, 0x3d, 0x1b, 0x67, 0x08, 0x20, 0x0d, 0x5f, 0xb0, 0x61, 0x86, 0xc0, 0xa7,
	0x1d, 0x6d, 0xb7, 0x45, 0x74, 0xda, 0x03, 0x7e, 0x70, 0xfc, 0xef, 0xe9, 0xf6, 0x63, 0x01, 0x8a,
	0x36, 0x6d, 0x29, 0x56, 0x58, 0x25, 0xd5, 0xa6, 0xa5, 0xd5, 0x46, 0xd5, 0x16, 0xeb, 0x84, 0x8c,
	0x22, 0x92, 0xc6, 0xbd, 0x25, 0x52, 0xa2, 0x11, 0xca, 0xb1, 0x3b, 0xea, 0xdd, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x85, 0x51, 0x84, 0x7c, 0x12, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoggerClient is the client API for Logger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoggerClient interface {
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
}

type loggerClient struct {
	cc *grpc.ClientConn
}

func NewLoggerClient(cc *grpc.ClientConn) LoggerClient {
	return &loggerClient{cc}
}

func (c *loggerClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, "/log.Logger/Log", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggerServer is the server API for Logger service.
type LoggerServer interface {
	Log(context.Context, *LogRequest) (*LogResponse, error)
}

// UnimplementedLoggerServer can be embedded to have forward compatible implementations.
type UnimplementedLoggerServer struct {
}

func (*UnimplementedLoggerServer) Log(ctx context.Context, req *LogRequest) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Log not implemented")
}

func RegisterLoggerServer(s *grpc.Server, srv LoggerServer) {
	s.RegisterService(&_Logger_serviceDesc, srv)
}

func _Logger_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/log.Logger/Log",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Logger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "log.Logger",
	HandlerType: (*LoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _Logger_Log_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log.proto",
}
